fix default value of project to be just "TAN"
PaulHuwe/roman_datamodels pull request #2
Opened 2023-12-19 17:05 UTC by stscieisenhamer

WIP [RCAL-704](https://jira.stsci.edu/browse/RCAL-704)

This resolves an issue with the default value of the `meta.wcsinfo.project` being assigned in the maker utilities.

2023-12-29 13:20 UTC, stscieisenhamer commented
There are many unresolved issues that I will be listing in the [RCAL-704](https://jira.stsci.edu/browse/RCAL-704) issue.

2024-01-26 21:00 UTC, PaulHuwe requested changes

2024-01-26 21:00 UTC, PaulHuwe commented on src/roman_datamodels/maker_utils/_common_meta.py
> +    meta = mk_basic_meta(**kwargs)
This will need removal and the appropriate keywords populated in the mosaic_basic maker utility.

2024-01-28 02:55 UTC, stscieisenhamer commented
Closing PR in expectation of a new one.

2024-01-28 02:55 UTC, closed without merging